[build]
    base = "//10.1 Styling and Cleanup/"
  publish = "build"
  command = "npm run build"
  functions = "functions"

[dev]
    framework = "#custom"
    command = "npm run start"
    targetPort = 3000